---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4874/workspace/MavAnsWeb/target/myansi-1.0-SNAPSHOT.jar"
        dest: "/opt/tomcat/webapps/myansi-1.0-SNAPSHOT.jar"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
